language: go

matrix:
  include:
    - go: "tip"
    - go: "1.x"
    - go: "1.12"
    - go: "1.11"
    - go: "1.10"
    - go: "1.9"
    - go: "1.8"
  allow_failures:
    - go: tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
